#
# Makefile
#
# Computer Science 50
# Problem Set 4
#

whodunit: whodunit.c Makefile
	clang -ggdb3 -Ispl/include -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o whodunit whodunit.c -Lspl/lib -lcs50 -lm

copy: copy.c Makefile
	clang -ggdb3 -Ispl/include -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o copy copy.c -Lspl/lib -lcs50 -lm

resize: resize.c Makefile
	clang -ggdb3 -Ispl/include -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o resize resize.c -Lspl/lib -lcs50 -lm
